[client]
showErrorDetails = false
toolbarMode = "minimal"

[server]
port = 8501
headless = true
runOnSave = true
enableXsrfProtection = true

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#31333F"
font = "sans serif"

[logger]
level = "error"
